default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: calm_waters_development
  username: root
  password: root

test:
  <<: *default
  database: calm_waters_test
  username: root
  password: root

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: calm_waters_production
  username: calm_waters
  password: <%= ENV['CALM_WATERS_DATABASE_PASSWORD'] %>
