default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: calm_waters_development
  username: root
  password: root

test:
  <<: *default
  database: calm_waters_test
  username: root
  password: root

production:
  <<: *default
  database: calm_waters_production
  username: root
  password: root
